# HPO Graph

In [1]:
import os
import sys
module_path = os.path.abspath(os.path.join('../..'))
if module_path not in sys.path:
    sys.path.append(module_path)
import configparser
import pandas as pd
pd.set_option('display.max_colwidth', None)
from util.graphdb_base import GraphDBBase

## Import Configuration File

In [2]:
config_file = "../../config.ini"
config = configparser.ConfigParser()
config.read(config_file)
neo4j_config = config["neo4j"]
uri = neo4j_config.get("uri")
user = neo4j_config.get("user")
password = neo4j_config.get("password")
encrypted = neo4j_config.getboolean("encrypted")
database = neo4j_config.get("database")
print(f"URI: {uri}")
print(f"User: {user}")
print(f"Password: {password}")
print(f"Encrypted: {encrypted}")
print(f"Database: {database}")

URI: bolt://localhost:7687
User: neo4j
Password: password
Encrypted: False
Database: hpo

In [3]:
gd = GraphDBBase()
gd._database = database

## Read Graph Data

In [4]:
def show_result_in_df(query, gd):
    with gd._driver.session(database=gd._database) as session:
        r = session.run(query)
        return pd.DataFrame.from_dict(r.data())

In [5]:
# Get diseases which have at least one abnormal phenotypic feature
query = """
MATCH (phe:HpoPhenotype)
WHERE phe.label = "Growth delay"
OR phe.label = "Large knee"
OR phe.label = "Sensorineural hearing impairment"
OR phe.label = "Pruritus"
OR phe.label = "Type I diabetes mellitus"
WITH phe
MATCH path=(dis:HpoDisease)-[:HAS_PHENOTYPIC_FEATURE]->(phe)
UNWIND dis as nodes
RETURN dis.id as disease_id, 
dis.label as disease_name,
collect(phe.label) as features,
count(nodes) as num_of_features
ORDER BY num_of_features DESC, disease_name
LIMIT 5
"""
show_result_in_df(query, gd)

,disease_id,disease_name,features,num_of_features
0,OMIM:619269,Ondontochondrodysplasia 2 with hearing loss and diabetes,"[Sensorineural hearing impairment, Pruritus, Growth delay, Large knee, Type I diabetes mellitus]",5
1,OMIM:618500,Holoprosencephaly 12 with or without pancreatic agenesis,"[Sensorineural hearing impairment, Growth delay, Type I diabetes mellitus]",3
2,OMIM:617248,"3-methylglutaconic aciduria, type VIII","[Sensorineural hearing impairment, Growth delay]",2
3,ORPHA:93925,Alobar holoprosencephaly,"[Sensorineural hearing impairment, Growth delay]",2
4,OMIM:301040,"Alpha-Thalassemia/mental retardation syndrome, X-linked","[Sensorineural hearing impairment, Growth delay]",2

# Reasoning Over Graph Data

In [ ]:
# Diseases connected to "Abnormal circulating carbohydrate concentration"

In [6]:
# Number of direct subclasses of "Abnormal circulating carbohydrate concentration"
query = """
MATCH (n:HpoPhenotype)<-[:SUBCLASSOF]-(m:HpoPhenotype)
WHERE n.label = "Abnormal circulating carbohydrate concentration"
RETURN COUNT(m) AS count
"""
show_result_in_df(query, gd)

   count
0     16

In [7]:
# Number of all subclasses of "Abnormal circulating carbohydrate concentration"
query = """
MATCH (n:HpoPhenotype)<-[:SUBCLASSOF*1..10]-(m:HpoPhenotype)
WHERE n.label = "Abnormal circulating carbohydrate concentration"
RETURN COUNT(m) AS count
"""
show_result_in_df(query, gd)

   count
0     22

In [8]:
# Get all disease which have anomalies related to "Abnormal circulating carbohydrate concentration"
query = """
MATCH (cat:HpoPhenotype {label: "Abnormal circulating carbohydrate concentration"})
CALL n10s.inference.nodesInCategory(cat, { 
    inCatRel: "HAS_PHENOTYPIC_FEATURE", subCatRel: "SUBCLASSOF"})
YIELD node as dis

MATCH (n:HpoPhenotype {label: "Abnormal circulating carbohydrate concentration"})
CALL apoc.path.expandConfig(n, {
        relationshipFilter: '<SUBCLASSOF',
        minLevel: 1,
        maxLevel: -1,
        uniqueness: 'RELATIONSHIP_GLOBAL'
    }) yield path
UNWIND nodes(path) as subclasses
WITH dis, n, collect(DISTINCT subclasses.label) as sub_anomalies

MATCH (dis)-[:HAS_PHENOTYPIC_FEATURE]->(phe:HpoPhenotype)
WITH DISTINCT dis.label as disease,
              sub_anomalies,
              collect(DISTINCT phe.label) as all_anomalies
RETURN disease,
       all_anomalies,
       [item IN all_anomalies WHERE item IN sub_anomalies] as anomalies_of_carb_concentration
ORDER BY size(anomalies_of_carb_concentration) DESC, disease
LIMIT 10
"""
show_result_in_df(query, gd)

,disease,all_anomalies,anomalies_of_carb_concentration
0,Galactosemia,"[Reduced erythrocyte galactose-1-phosphate uridylyltransferase activity, Hyperchloremic metabolic acidosis, Galactosuria, Delayed speech and language development, Jaundice, Decreased liver function, Hypergalactosemia, Increased level of galactitol in red blood cells, Elevated circulating aspartate aminotransferase concentration, Hypergonadotropic hypogonadism, Premature ovarian insufficiency, Bilateral tonic-clonic seizure, Neonatal onset, Elevated circulating alanine aminotransferase concentration, Hemolytic anemia, Increased level of galactitol in urine, Feeding difficulties, Failure to thrive, Generalized hypotonia, Albuminuria, Vomiting, Diarrhea, Cataract, Autosomal recessive inheritance, Cirrhosis, Increased level of galactitol in plasma, Hepatomegaly, Increased level of galactonate in red blood cells, Metabolic acidosis, Intellectual disability, Aminoaciduria]","[Hypergalactosemia, Increased level of galactitol in red blood cells, Increased level of galactitol in plasma]"
1,Galactokinase deficiency,"[Feeding difficulties, Speech apraxia, Seizure, Hypergalactosemia, Microcephaly, Failure to thrive, Hepatosplenomegaly, Small for gestational age, Premature ovarian insufficiency, Increased level of galactitol in plasma, Hypercholesterolemia, Intellectual disability, Increased level of galactitol in urine, Cataract, Hypergonadotropic hypogonadism, Sensorineural hearing impairment, Abnormal circulating enzyme concentration or activity, Hypoglycemia, Neonatal asphyxia, Hepatomegaly, Nuclear cataract, Motor delay, Reduced circulating complement concentration, Premature birth, Hyperinsulinemia, Psychomotor deterioration]","[Hypergalactosemia, Increased level of galactitol in plasma]"
2,Ribose 5-phosphate isomerase deficiency,"[Increased level of D-threitol in plasma, Increased level of ribose in urine, Increased CSF ribose concentration, Spasticity, Increased CSF D-threitol concentration, Nystagmus, Decreased level of erythritol in urine, Increased level of ribitol in urine, Dysarthria, Increased CSF xylitol concentration, Seizure, Elevated circulating ribitol concentration, Increased CSF ribitol concentration, Ataxia, Optic atrophy, Global developmental delay, Increased level of D-threitol in urine, Increased level of xylitol in urine, Autosomal recessive inheritance, Elevated brain polyol compounds by MRS, Leukoencephalopathy, Sensorimotor neuropathy, Polyneuropathy, Incoordination, Decreased CSF erythritol concentration]","[Increased level of D-threitol in plasma, Elevated circulating ribitol concentration]"
3,Congenital enterocyte heparan sulfate deficiency,"[Diarrhea, Weight loss, Hematochezia, Dehydration, Abnormal circulating polysaccharide concentration, Abnormal circulating protein concentration, Protein-losing enteropathy, Abdominal distention, Edema, Hypoalbuminemia]",[Abnormal circulating polysaccharide concentration]
4,"Diabetes mellitus, insulin-dependent-1","[Hyperglycemia, Decreased level of 1,5 anhydroglucitol in serum, Polyphagia, Ketoacidosis, Polydipsia, Autoimmunity, Polyuria, Diabetes mellitus]","[Decreased level of 1,5 anhydroglucitol in serum]"
5,Fanconi-Bickel syndrome,"[Osteomalacia, Ketonuria, Elevated gamma-glutamyltransferase level, Proteinuria, Postprandial hyperglycemia, Poor appetite, Abdominal distention, Global developmental delay, Hepatomegaly, Hypophosphatemia, Rickets, Hypokalemia, Elevated circulating alkaline phosphatase concentration, Fasting hypoglycemia, Hypouricemia, Hyperphosphaturia, Chronic acidosis, Elevated circulating aspartate aminotransferase concentration, Malabsorption, Postnatal growth retardation, Neonatal onset, Renal tubular dysfunction, Hypergalactosemia, Elevated circulating alanine aminotransferase concentration, Generalized aminoaciduria, Autosomal recessive inheritance, Infantile onset, Glycosuria, Hypercalciuria, Intrahepatic cholestasis, Failure to thrive, Beta 2-microglobulinuria, Hyperbilirubinemia, Acidosis, Reduced subcutaneous adipose tissue, Increased serum bile acid concentration, Impairment of galactose metabolism]",[Hypergalactosemia]
6,Galactokinase deficiency with cataracts,"[Reduced erythrocyte galactokinase activity, Prolonged neonatal jaundice, Increased intracranial pressure, Autosomal recessive inheritance, Cataract, Hypergalactosemia, Galactosuria]",[Hypergalactosemia]
7,Galactose epimerase deficiency,"[Failure to thrive, Childhood onset, Aminoaciduria, Hepatomegaly, Delayed gross motor development, Autosomal recessive inheritance, Splenomegaly, Hypergalactosemia, Delayed speech and language development, Decreased beta-galactosidase activity, Hypotonia, Intellectual disability, Generalized hypotonia, Global developmental delay, Jaundice, Galactosuria, Vomiting, Sensorineural hearing impairment]",[Hypergalactosemia]
8,Galactose mutarotase deficiency,"[Failure to thrive, Cholestasis, Decreased liver function, Cataract, Hepatomegaly, Impairment of galactose metabolism, Abnormality of the nervous system, Hypergalactosemia, Abnormal circulating enzyme concentration or activity, Sepsis]",[Hypergalactosemia]
9,Galactosemia IV,"[Global developmental delay, Hepatomegaly, Autosomal recessive inheritance, Neonatal onset, Prolonged neonatal jaundice, Cataract, Hypergalactosemia]",[Hypergalactosemia]

In [9]:
query = """
MATCH (n:HpoPhenotype {label: "Abnormal circulating carbohydrate concentration"})
CALL apoc.path.expandConfig(n, {
        relationshipFilter: '<SUBCLASSOF',
        minLevel: 1,
        maxLevel: -1,
        uniqueness: 'RELATIONSHIP_GLOBAL'
    }) yield path
UNWIND nodes(path) as subclasses
WITH n, collect(DISTINCT subclasses) as uniques
UNWIND uniques as unique_subclasses
WITH n, unique_subclasses
WHERE n <> unique_subclasses
RETURN DISTINCT unique_subclasses.label
"""
show_result_in_df(query, gd)

                                           unique_subclasses.label
0   Elevated circulating trihydroxycholestanoic acid concentration
1                 Increased level of galactitol in red blood cells
2                          Increased level of galactitol in plasma
3                  Decreased level of 1,5 anhydroglucitol in serum
4                          Increased level of D-threitol in plasma
5                       Abnormal circulating heparan sulfate level
6                  Decreased circulating sialic acid concentration
7                    Elevated circulating arabinitol concentration
8                    Elevated circulating erythritol concentration
9                 Decreased circulating myo-inositol concentration
10                          Increased serum sorbitol concentration
11                                   Elevated cancer Ag 19-9 level
12                             Abnormal circulating glycerol level
13                      Elevated circulating ribitol concentration
14                                               Hypergalactosemia
15               Abnormal circulating polysaccharide concentration
16                     Decreased circulating heparan sulfate level
17                     Increased circulating heparan sulfate level
18                                               Hyperglycerolemia
19                            Decreased circulating glycerol level
20              Abnormal circulating hyaluronic acid concentration
21              Elevated circulating hyaluronic acid concentration